### ISSUE TITLE
实验网站访问不了啊

### ISSUE THREAD

**Issue by yangshuolll** [haozi/xss-demo#3]
这个网址访问不了啊，https://xss.haozi.me/

还有想问下，centos下载了yarn，然后安装不了实验环境啊。
在控制台运行yarn报这个错误

/usr/share/yarn/lib/v8-compile-cache.js:3
const Module = require('module');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:6:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by haozi-de** [comment]
服务器挂了，目前移动到日本机房了。
你的问题是 nodejs 版本太低

**Comment by haozi** [comment]
服务器挂了，目前移动到日本机房了。
你的问题是 nodejs 版本太低
